services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: newschool
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-apache.conf
        ports:
            - "8000:80"
        networks:
            - newschool-network

networks:
    newschool-network:
        driver: bridge
