services:
    newschool:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: newschool
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
