version: '3.8'

services:
    # Serviço PHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: newschool
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - newschool-network

    # Serviço Nginx
    webserver:
        image: nginx:alpine
        container_name: newschool-ranking-api-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - newschool-network

networks:
    newschool-network:
        driver: bridge
